const employees = [
    {
      id: '1',
      name: 'James King',
      position: 'President and CEO',
      img: '/images/James_King.jpg',
      officePhone: '781-000-0002',
      mobilePhone: '617-000-0002',
      email: 'jtaylor@fakemail.com',
      // color: '#FEB692',
    },
    {
      id: '2',
      name: 'Julie Taylor',
      position: 'VP of Marketing',
      img: '/images/Julie_Taylor.jpg',
      officePhone: '781-000-0002',
      mobilePhone: '617-000-0002',
      email: 'jtaylor@fakemail.com',
      // color: '#F8CEEC',
    },
    {
      id: '3',
      name: 'Eugene Lee',
      position: 'CFO',
      img: '/images/Eugenee_Lee.jpg',
      officePhone: '781-000-0002',
      mobilePhone: '617-000-0002',
      email: 'jtaylor@fakemail.com',
      // color: '#B8F3FF',
    },
    {
      id: '4',
      name: 'John Williams',
      position: 'VP of Engineering',
      img: '/images/John_Williams.jpg',
      officePhone: '781-000-0002',
      mobilePhone: '617-000-0002',
      email: 'jtaylor@fakemail.com',
      // color: '#FFF8DC',
    },
    {
      id: '5',
      name: 'Ray Moore',
      position: 'VP of Sales',
      img: '/images/Ray_Moore.jpg',
      officePhone: '781-000-0002',
      mobilePhone: '617-000-0002',
      email: 'jtaylor@fakemail.com',
      // color: '#D0F0C0',
    },
    {
      id: '6',
      name: 'Paul Jones',
      position: 'QA Manager',
      img: '/images/Paul_Jones.jpg',
      officePhone: '781-000-0002',
      mobilePhone: '617-000-0002',
      email: 'jtaylor@fakemail.com',
      // color: '#FEB692',
    },
  ];
  
  export default employees;

        // img: 'https://www.nicepng.com/png/detail/249-2492113_work-profile-user-default-female-suit-comments-default.png',
